### PR TITLE
Fix #3: handle null props

### LINKED ISSUE #3: PureRenderMixin crashes on undefined/null props
:blush:

### PR DESCRIPTION
**Pull request by benjie**
The PureRenderMixin was not correctly dealing with null props (in fact, it was trying to access `_immutableBackboneModel` of `undefined` which is clearly very bad). This PR resolves this, handling both a prop going from null to not null and back again.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -182,10 +190,14 @@ exports.PureRenderMixin = {
...
       modelOrCollection = newObjects[key];
-      if (modelOrCollection._immutableBackboneModel) {
-        changed = updateStash(newStash, oldStash, key, modelOrCollection, ['attributes']) || changed;
-      } else if (modelOrCollection._immutableBackboneCollection) {
-        changed = updateStash(newStash, oldStash, key, modelOrCollection, ['models']) || changed;
+      var isImmutableModel = modelOrCollection && modelOrCollection._immutableBackboneModel;
+      var isImmutableCollection = modelOrCollection && modelOrCollection._immutableBackboneCollection;
+      var wasImmutableModel = oldStash[key] && oldStash[key]._type === 'model';
+      var wasImmutableCollection = oldStash[key] && oldStash[key]._type === 'collection';
+      if (isImmutableModel || (!isImmutableCollection && wasImmutableModel)) {
```
Comment (tvararu) [inline index.js]: :tada:

**Comment by tvararu** [comment]
I can't speak for the logic as I don't fully grok the edge case this papers over, but the code looks sane.
